---
version: '3.3'
services:
  app:
    build: https://github.com/m912u/app42fork.git
    links:
      - db
    ports:
      - "8080:8080"
  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

