---
version: '3.3'
services:
  app:
    build: .
    links:
      - db
    ports:
      - "8080:8080"
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dd
